updated depends_on for Java to use OpenJDK (:java was failing)
yugabyte/homebrew-yugabytedb pull request #17
Opened 2021-05-12 00:31 UTC by thtmnisamnstr

Running `brew tap yugabyte/yugabytedb` fails. I updated the `depends_on :java` dependiencies in your Homebrew tap to `depends_on "openjdk"`, as the `depends_on :java` dependencies are no longer valid.

**Terminal Output before PR**
```
==> Tapping yugabyte/yugabytedb
Cloning into '/usr/local/Homebrew/Library/Taps/yugabyte/homebrew-yugabytedb'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 151 (delta 12), reused 35 (delta 9), pack-reused 108
Receiving objects: 100% (151/151), 36.17 KiB | 1.21 MiB/s, done.
Resolving deltas: 100% (38/38), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/yugabyte/homebrew-yugabytedb/Formula/yugabytedb.rb
yugabytedb: Unsupported special dependency :java
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/yugabyte/homebrew-yugabytedb/Formula/yugabytedb-client.rb
yugabytedb-client: Unsupported special dependency :java
Error: Cannot tap yugabyte/yugabytedb: invalid syntax in tap!
```

2021-05-13 09:57 UTC, bhavin192 requested changes
Thank you @thtmnisamnstr for sending this pull request, just to make sure we install a compatible JDK, can you please make it `openjdk@8` instead of `openjdk` ?

2021-05-13 09:58 UTC, bhavin192 commented
Other references related to this issue: 
- https://brew.sh/2020/12/01/homebrew-2.6.0/
- https://github.com/klaytn/homebrew-klaytn/pull/6
- https://github.com/Homebrew/brew/pull/9209

2021-05-13 13:38 UTC, thtmnisamnstr commented
@bhavin192 I updated both formula to use “openjdk@8”.

2021-05-13 17:25 UTC, svarnau approved these changes
Looks good to me. I can verify the client formula worked for me with this change.

2021-05-14 11:18 UTC, bhavin192 approved these changes

2021-05-14 19:46 UTC, merged